flowchart LR
%% generated in 0.00s
    subgraph scripts__build_site
        scripts__build_site__page["page"]
        scripts__build_site__md["md"]
        scripts__build_site__md_to_html_links["md_to_html_links"]
    end
    subgraph scripts__check_node_types
        scripts__check_node_types___load_registry_ids["_load_registry_ids"]
        scripts__check_node_types__main["main"]
    end
    scripts__build_site__page --> scripts__build_site__md_to_html_links
    scripts__build_site__page --> scripts__build_site__md
    scripts__check_node_types__main --> scripts__check_node_types___load_registry_ids
